Repository raspiblitz/raspiblitz, pull requests merged in 2021-12, with the labels that each got.

#2651 #2400 adjust command prompt
  build_sdcard.sh
Labels: final testing

#2734 [Review] fix(deps): Bumps base image to bullseye
  build_sdcard.sh
Labels: final testing

#2711 [WIP] 2669tor - improve tor configuration
  .shellcheckrc
  build_sdcard.sh
  home.admin/_provision_.sh
  home.admin/config.scripts/tor.install.sh
  home.admin/config.scripts/tor.network.sh
  home.admin/config.scripts/tor.onion-service.sh
Labels: teamdiscuss

#2617 Integrate Tallycoin Connect
  README.md
  home.admin/_provision_.sh
  home.admin/assets/nginx/sites-available/tallycoin_connect_ssl.conf
  home.admin/assets/nginx/sites-available/tallycoin_connect_tor.conf
  home.admin/assets/nginx/sites-available/tallycoin_connect_tor_ssl.conf
  home.admin/config.scripts/bonus.tallycoin-connect.sh
Labels: final testing

#2830 Update broken links / use GitHub links.
  FAQ.md
  README.md
  build_sdcard.sh
Labels: documentation
